# Generated by Django 3.2.4 on 2021-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_experience_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='comments',
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
