# Generated by Django 3.2.4 on 2021-08-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_experience_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
